### PR TITLE
155820624: DetailLayoutActivity

### PR DESCRIPTION
**Pull request by Kalela**
# What does this PR do?
- Creates the layout for the DetailLayout activity.
- Allows DetailLayoutActivity to be launched from the MainActivity.
### Screenshot
ezgif com-optimize

### How should this be manually tested?
1. Clone the repo to your local machine.
2. Open the project with Android Studio.
3. Run an emulator or adb connection and run the app.
4. Tap on one of the developers in the main page to see the details activity.

### What are the relevant pivotal tracker stories?
- 155820645
Create layout file for DetailActivity
- 155820624
Launch the DetailActivity from the MainActivity

### CODE REVIEW

**Comment by Jak-Sidious** [comment]
1. As far as the screenshots go you can either do a screencast n convert to a .gif file directly from the android studio emulator or u can do a screencast using quicktime player n then convert to a .gif file using this site[https://ezgif.com/]. 
However, remember that with your recordings they should be 30seconds or less for a gif.
2. Secondly how come the text for the developer name is an editable field I believe it should just be a display only field 
screen shot 2018-06-29 at 13 14 13

Do make the necessary changes as soon as possible

3. How come you change the base branch from master to develop for each and every PR? Please shed some light on this for me.

**Comment by Kalela** [comment]
@Jak-Sidious Check the changes now. Switched the editext. For the master/development branch change, it's a mistake I keep making. I impulsively create the PR with master as the base branch then change to the correct development branch.

**Comment by Jak-Sidious** [comment]
Just one more thing, Can you ensure that the onclick listener applies to the entire item as opposed to just the picture being clickable

**Comment by Kalela** [comment]
It actually applies to the whole item. Try it again. Will add an onclick animation for better ux.

**Comment by Jak-Sidious** [comment]
Seen. good job with this one.
LGTM

**Pull request merged**
