### PR TITLE
#156185242 Unit and UI tests

### PR DESCRIPTION
**Pull request by Kalela**
# What does this PR do?
Sets up initial unit and UI tests for the android level up project.

### How should this be manually tested?
1. Clone the repo.
2. cd into the base directory of the project.
2. Run ``` ./gradlew test ```  and ``` ./gradlew createDebugCoverageReport ``` to generate the coverage report.

NB: Check coverage report in app/build/reports/coverage/index.html.
image

### What are the relevant pivotal tracker stories?
156185242
Unit Test your Code
157354404
UI Test your Code

### CODE REVIEW

**Comment by Jak-Sidious** [comment]
You need to state where the test reports are stored when they are generated and stored within the path.
Secondly, did you use jacoco to create a unified test report.

**Comment by Kalela** [comment]
Working on it

**Comment by Jak-Sidious** [comment]
You need to state which commands generate/create which files where in your case the 

1. `./gradlew test` command creates the  `app/build/reports/tests` report directories
2. `./gradlew createDebugCoverageReport` generates the `app/build/reports/androidTests` and `app/build/reports/coverage` report directories.

Make this change then we can proceed

**Comment by Jak-Sidious** [comment]
Additionally, you can add sample outputs of the reports generated with each command

**Comment by Kalela** [comment]
It only does the report for UI tests. ``` ./gradlew createDebugCoverageReport ```

**Comment by Kalela** [comment]
That's the only report that is generated.

**Pull request closed without merging**
