### PR TITLE
#155965773 Github users adapter

### PR DESCRIPTION
**Pull request by Kalela**
# What does this PR do?
Creates an adapter ``` GithubUsersAdapter.java ``` that leverages the retrofit instance to render Java developers in Nairobi using the github api.
### Screenshots
ezgif com-optimize

### How should this be manually tested?
- Clone the repo.
- Open the project in android studio.
- Run the project using an emulator or adb.
- Try searching for developers shown on Github to confirm they are from github api.

#### 155965773
Create the GithubUsersAdapter

#### 155965831
Display List of Github Users

### CODE REVIEW

**Comment by Jak-Sidious** [comment]
Just a few things to note 
1. I see you implemented the change as we discussed.
2. Is it possible to get the recycler view to span the entire screen as the whitespace at the bottom is a bit of an eyesore.
screen shot 2018-07-06 at 15 56 30
3. Can you increase on the image sizes in the recycler view as they are very tiny right now.

**Comment by Kalela** [comment]
Lemme work on that.

**Comment by Jak-Sidious** [comment]
Going forward, as far as commit and PR's go, it is in your best interests to start following these as best practises [Best Practises](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices)

**Comment by Kalela** [comment]
check out how it looks now

**Comment by Jak-Sidious** [comment]
still not spanning the entire screen and I've tested it on two different devices
screen shot 2018-07-09 at 17 36 37

**Comment by Kalela** [comment]
Fixed it now. Check it out.

**Comment by Jak-Sidious** [comment]
You fixed the display issue. 
Good Job.
LGTM

**Pull request merged**
